---
# set_fau_ntp_servers/tasks/main.yml

#
# SLES15 or newer with chronyd
#

- name: 'Remove /etc/chrony.d/opensuse.conf'
  ansible.builtin.file:
    path: '/etc/chrony.d/opensuse.conf'
    state: 'absent'
  when: '(ansible_os_family == "Suse" and ansible_distribution_major_version > "12")
        or ansible_distribution == "openSUSE MicroOS"'
  notify:
    - 'Restart chronyd'

- name: 'Create configuration file for chrony'
  ansible.builtin.template:
    src: 'etc_chrony.d_fau_servers.conf.j2'
    dest: '/etc/chrony.d/fau_servers.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: '(ansible_os_family == "Suse" and ansible_distribution_major_version > "12")
        or ansible_distribution == "openSUSE MicroOS"'
  notify:
    - 'Restart chronyd'

#
# SLES12 with ntpd
#
- name: 'SLES12 only: Add FAU servers to ntp.conf'
  ansible.builtin.lineinfile:
    path: '/etc/ntp.conf'
    regexp: "{{ item }}"
    line: "server {{ item }} iburst"
    owner: 'root'
    group: 'ntp'
    mode: '0640'
  when:
    - 'ansible_distribution == "SLES"'
    - 'ansible_distribution_major_version == "12"'
  with_items:
    - "{{ list_of_ntp_servers }}"
  notify:
    - 'Restart ntpd'
