---
# set_fau_ntp_servers/handlers/main.yml

- name: 'Restart chronyd'
  ansible.builtin.service:
    name: "{{ chronyd_service }}"
    state: 'restarted'
    enabled: true
  when:
    - '(ansible_distribution == "SLES" or ansible_distribution == "openSUSE Leap")'
    - 'ansible_distribution_major_version | int > 12'

- name: 'Restart ntpd'
  ansible.builtin.service:
    name: "{{ ntpd_service }}"
    state: 'restarted'
    enabled: true
  when:
    - 'ansible_distribution == "SLES"'
    - 'ansible_distribution_major_version | int == 12'
