---
# set_fau_ntp_servers/handlers/main.yml

- name: "restart chronyd"
  service:
    name: "{{ chronyd_service }}"
    state: "restarted"
    enabled: true
  when: 'ansible_distribution == "SLES" and ansible_distribution_major_version > "12"'
